timezone: Europe/Amsterdam
markdown: redcarpet
sass:
    sass_dir: _sass
    style: :compressed

gems:
    - jekyll-feed

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
