timezone: Europe/Amsterdam
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
sass:
    sass_dir: _sass
    style: :compressed

gems:
    - jekyll-feed
    - jekyll-paginate

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
